{
 "title": "websocket server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "msg sent rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(ws_msg_sent[$__interval])", "legendFormat": "__auto" },
    {
     "expr": "sum(rate(ws_msg_sent[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "msg broadcast rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ws_msg_count[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(ws_msg_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go thread count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ws connect latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(le) (increase(ws_http_server_request_latency_ms_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}